<?php $cart = $this->cart(); ?>
<?php if ($cart->isActive()): ?>
  <?php $cartId = $this->source . '|' . $this->id; ?>
  <span class="btn-bookbag-toggle" data-cart-id="<?=$this->escapeHtmlAttr($this->id)?>" data-cart-source="<?=$this->escapeHtmlAttr($this->source)?>">
    <a href="#" class="cart-add result-link icon-link hidden<?php if (!$cart->contains($cartId)): ?> correct<?php endif ?>">
      <?=$this->icon('user-checked-out', 'icon-link__icon') ?>
      <span class="icon-link__labels"></span>
    </a>
    <a href="#" class="cart-remove result-link icon-link hidden<?php if ($cart->contains($cartId)): ?> correct<?php endif ?>">
      <?=$this->icon('search-filter-remove', 'icon-link__icon') ?>
      <span class="icon-link__labels"></span>
    </a>
  </span>
<?php endif; ?>
