<?php $this->headTitle($this->translate('Aviso de Privacidad')); ?>

<div class="container mt-5">
    <h1 class="text-center display-4 mb-4">Aviso de Privacidad</h1>

    <div class="row justify-content-center">
        <div class="col-12 col-lg-10">
            <div class="card p-4 mb-5 shadow-sm">
                <p>
                    En términos de lo previsto en la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, le solicitamos lectura cuidadosa del presente Aviso de Privacidad, ya que la aportación que haga de sus datos personales, sea a través de medios físicos o digitales institucionales, constituye la aceptación de estos Términos y Condiciones, en consecuencia, su autorización al tratamiento de sus datos personales.
                </p>
                <p>
                    La Universidad Madero en su relación con aspirantes y estudiantes, padres de familia y tutores, empleados, proveedores y prestadores de servicios, y egresados, opera datos personales de diversa índole para el cumplimiento de sus obligaciones.
                </p>
                <p>
                    La UMAD en respeto del derecho fundamental de todo ser humano a la privacidad y atendiendo el marco jurídico mexicano, en relación a los registros recabados y al tratamiento de datos asociados a los mismos, se sujetará a lo dispuesto por la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, a las disposiciones que de ella emanen, a la correlativa legislación vigente en el ámbito local y a las normas y reglamentos institucionales aplicables.
                </p>
                <p>Los datos personales en posesión de la UMAD, aquellos que deriven de la prestación de servicios educativos o de la relación laboral entre el titular y la UMAD y los que la misma obtenga de otras fuentes permitidas por la ley, serán transmitidos a las autoridades competentes, locales y federales, exclusivamente para el ejercicio de sus atribuciones, así como a entidades y dependencias externas a la institución, públicas y privadas, que los requieran para ejercer sus funciones, en cuyo caso la información será disociada de su titular siempre que sea posible.

Principales finalidades y tratamiento por terceros de datos personales</p>
                    <h3>1.Aspirantes y Estudiantes</h3>
                    <p>Los datos personales, aún los sensibles, serán protegidos y serán incorporados y tratados, según corresponda, en los sistemas de información de la UMAD y de terceros que la institución contrate para que le provean de productos y servicios, cuando esto sea necesario.

                    Los terceros a los que se refiere el párrafo anterior son aquellos con quienes la UMAD tenga contratados servicios para el procesamiento de datos, para acreditaciones y certificaciones, para realizar estudios socio-económicos cuando sean solicitadas becas o apoyos económicos, para que UMAD ejerza sus derechos, así como para ofrecer servicios de la UMAD, de cualquier tipo. De igual manera, datos personales de contacto como nombre, domicilio, teléfono, y correo electrónico, podrán ser utilizados por la UMAD para que pueda recibir información sobre nuestros servicios, eventos culturales, deportivos, académicos, proyectos sociales.

                    De entre los terceros a los que la UMAD podrá transferir sus datos personales, se encuentran, de manera enunciativa más no limitativa, instituciones y universidades, en cuyo caso sólo proporcionará los datos que sean indispensables para la actividad o servicio específico que dichas instituciones realizarán.

                    En el caso de datos personales de menores de edad, será el padre, madre o tutor del titular quien los proporcione, consienta sobre su tratamiento y ejerza los derechos de acceso, rectificación, cancelación, oposición, divulgación, limitación de uso o revocación del consentimiento a que se refieren la ley y el presente aviso.</p>
                <h3>2. Empleados</h3>
                <p>Los datos personales en posesión de la UMAD, incluso los sensibles, aquellos que deriven de la relación laboral entre el titular y la UMAD y los que la misma obtenga de otras fuentes permitidas por la ley, tienen como finalidades principales las de identificar, localizar y contactar al titular, así como la operación y administración de su expediente, en los ámbitos laboral, académico, cultural, deportivo, de salud y cualquier otro de los que conforman los servicios que ofrecen la UMAD y terceros que la misma contrate para que le provean de servicios; la investigación para la toma de decisiones en los procesos de planeación y evaluación institucionales; así como para el debido cumplimiento de las obligaciones de índole legal que le correspondan a la UMAD antes las dependencias gubernamentales.

                De entre los terceros a los que la UMAD podrá transferir sus datos personales, se encuentran, de manera enunciativa más no limitativa, instituciones y universidades, en cuyo caso sólo proporcionará los datos que sean indispensables para la actividad o servicio específico que dichas instituciones realizarán.</p>
                
                <h3>3. Proveedores y Prestadores de Servicios</h3>
                <p>Los datos personales en posesión de la UMAD, incluso los sensibles, aquellos que deriven de la relación entre el titular y la UMAD y los que la misma obtenga de otras fuentes permitidas por la ley, tienen como finalidades principales las de identificar, localizar y contactar al titular, así como la operación y administración de su expediente, la investigación para la toma de decisiones en los procesos de planeación y evaluación institucionales y el cumplimiento de obligaciones de carácter legal.</p>
                
                <h3>4. Egresados</h3>
                <p>Cuando al egresado de la UMAD así le convenga para continuar recibiendo beneficios de integración, bolsa de trabajo, oferta académica y demás servicios actuales y futuros que desarrolle la UMAD, los datos personales, aún los sensibles, serán protegidos y serán incorporados y tratados, según corresponda, en los sistemas de información de la UMAD y de terceros que la institución contrate para que le provean de productos y servicios, cuando esto sea necesario.

                La UMAD se compromete a no transferir su información personal a terceros sin su consentimiento, salvo las excepciones previstas en el artículo 37 de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, así como a realizar esta transferencia en los términos que fija dicha ley. Si usted no manifiesta de manera formal y por escrito su oposición para que sus datos personales sean transferidos, se entenderá que ha otorgado su consentimiento para ello.</p>
                
                <h3>
                    Autoridad encargada de Datos Personales
</h3>
                <p>
                    El área responsable de los datos personales en la Universidad Madero es el Comité de Protección de Datos Personales, conformado por el Vicerrector de Servicios Académicos, la Directora Administrativa y el Jefe de Sistemas, dicho comité tiene domicilio en Camino Real a Cholula 4212 Col. Ex Hacienda La Concepción Buenavista C. P. 72150 Puebla, México, y/o puede ser contactado a través del correo electrónico <a href="mailto:datospersonales@umad.edu.mx" class="text-primary">datospersonales@umad.edu.mx</a>. Dicho comité tiene la facultad para asesorarle en el ejercicio de sus derechos.
                </p>
                <h3>Derechos de acceso, rectificación, cancelación u oposición</h3>
                <p>Si usted desea ejercer sus derechos de acceso, rectificación, cancelación u oposición vinculados a sus datos de carácter personal, usted o su representante legal deberá presentar su solicitud vía correo electrónico a la dirección postal del comité facultado y/o al correo electrónico datospersonales@umad.edu.mx

                El Comité de Protección de Datos Personales dará trámite a las solicitudes recibidas y dará respuesta en un plazo de 20 días hábiles contados a partir de la fecha en que se reciba la solicitud de acceso, rectificación, cancelación u oposición de sus datos personales. Si la solicitud procede, se hará efectiva en un plazo no mayor a 15 días hábiles siguientes a la fecha en que se comunique la respuesta anterior. El plazo podrá ser ampliado por una sola vez y por un periodo igual cuando existan hechos que lo justifiquen.

                Su solicitud (sea de acceso, rectificación, cancelación u oposición) deberá contener la siguiente información:
                    </p>
                 
                    <ul>
  <li>Nombre completo, domicilio y correo electrónico del solicitante, el cual será utilizado para dar respuesta a la solicitud correspondiente.</li>
  <li>Copia simple de identificación oficial con fotografía o, en su caso, la representación legal quien estuviera actuando en su nombre.</li>
  <li>Descripción clara y precisa de los datos personales respecto de los cuales busque ejercer alguno de los derechos de acceso, rectificación, cancelación y oposición.</li>
  <li>Referir cualquier otro dato o exhibir cualquier otro documento que permita facilitar la localización de sus datos personales.</li>
  <li>Firma del titular de los datos.</li>
</ul>

                    <p> 
                En caso de solicitar la rectificación de datos personales, también deberá indicar las modificaciones a realizar así como proporcionar la documentación que sustente su petición.
                </p>

                    <h3>Plazos de conservación de los datos personales</h3>
                    <p>Los plazos de conservación de sus datos de carácter personal no excederán de aquellos necesarios para el cumplimiento de las finalidades descritas. Una vez cumplidas las mismas, y cuando no exista disposición legal que establezca lo contrario, la UMAD procederá a la cancelación de sus datos personales.</p>
                <h3>
                    Cambios al Aviso de Privacidad
                </h3>
                <p>
                    La UMAD se reserva el derecho de efectuar modificaciones o actualizaciones en cualquier momento al presente aviso de privacidad y dando 30 días a los interesados para recibir sus observaciones. Dichas modificaciones se darán a conocer a los titulares de datos personales a través del portal web institucional <a href="http://www.umad.edu.mx" target="_blank" class="text-primary">www.umad.edu.mx</a>.
                </p>
                <p class="text-muted text-right">
                    El presente Aviso de Privacidad tiene vigencia a partir del día 12 de enero de 2015.
                </p>
            </div>
        </div>
    </div>
</div>