<?php $this->headTitle($this->translate('Contacto')); ?>

<div class="container mt-5 mb-2">
    <h1 class="text-center display-4 mb-5"><?php echo $this->transEsc('Contacto'); ?></h1>
    
    <div class="row">
        <div class="col-12 col-md-6 mb-4">
            <div class="p-4 bg-light border border-primary rounded">
                
                    <h2 class="text-primary">Dirección:</h2>
                    <h4>
                    Camino Real a Cholula 4212<br>
                    Col. Exhacienda La Concepción Buenavista<br>
                    C.P.72150, Puebla, México
                    </h4>
                
                    <h2 class="text-primary">Teléfono:</h2>
                    <h4>
                    (+52) 222 141 5959<br>
                    (+52) 222 141 5962
                    </h4>
                    <h2 class="text-primary">Email:</h2>
                    <h3 class="mb-2">
                    <a href="mailto:dulcevc@umad.edu.mx" class="text-primary">dulcevc@umad.edu.mx</a>
                    </h3>
            </div>
        </div>
    </div>
</div>