<?php
$this->headScript()->appendFile('index.js');

$url = 'http://localhost:8983/solr/biblio/select?q=*:*&facet=true&facet.pivot=institution,index_str_mv&facet.limit=-1&rows=0';

$json = file_get_contents($url);

if ($json === false) {
    die('Error al obtener los datos.');
}

$data = json_decode($json, true);


// Nombre en solr => nombre para mostrar
$institutions = [
    "Estudios de Asia y África" => "Estudios de Asia y África",
    "Historia Mexicana" => "Historia Mexicana",
    "Foro Internacional" => "Foro Internacional",
    "Estudios Sociológicos" => "Estudios Sociológicos de El Colegio de México",
    "Estudios Demográficos y Urbanos" => "Estudios Demográficos y Urbanos",
    "Cuadernos de Lingüística" => "Cuadernos de Lingüística de El Colegio de México",
    "Nueva Revista de Filología Hispánica" => "Nueva Revista de Filología Hispánica",
    "Estudios de Género" => "Revista Interdisciplinaria de Estudios de Género de El Colegio de México",
    "Estudios Económicos" => "Revista Estudios Económicos de El Colegio de México"
];

$indexData = [];
$numCategories = [];

foreach ($institutions as $key => $value) {
    $indexData[$key] = []; // Cada institución tiene un array de datos vacío inicialmente
    $numCategories[$key] = 0; // Numero de categorias
}

// Recorremos las instituciones devueltas por Solr
if (isset($data['facet_counts']['facet_pivot']['institution,index_str_mv'])) {
    foreach ($data['facet_counts']['facet_pivot']['institution,index_str_mv'] as $institution) {
        $institutionName = $institution['value'];
        
        if (array_key_exists($institutionName, $institutions)) {
            $indexValues = [];
            
            if (isset($institution['pivot'])) {
                foreach ($institution['pivot'] as $pivot) {
                    $indexValues[] = $pivot['value'];
                }
            }
                        $indexData[$institutionName] = $indexValues;
            $numCategories[$institutionName] = count($indexValues);
        }
    }
} else {
    echo "No se encontró el campo en solr";
}

?>

<h2>Índices</h2>
<div class="maindiv">
    <div class="accordion">
        <?php foreach ($institutions as $institution => $Name): ?>
            <div class="accordion-item">
                <button data-target="content-<?= htmlspecialchars($institution) ?>">
                    <span class="button-text"><?= htmlspecialchars($Name) ?></span>
                    <span class="content-number"><?= $numCategories[$institution] ?></span>
                    <i class="fa fa-chevron-down"></i>
                </button>
            </div>
        <?php endforeach; ?>
    </div>

    <!-- Contenido de las categorías dentro del acordeón -->
    <?php foreach ($institutions as $institution => $Name): ?>
        <div id="content-<?= htmlspecialchars($institution) ?>" class="accordion-content">
            <?php if (!empty($indexData[$institution])): ?>
                <ul class="category-list">
                    <!-- Generar la lista de categorías (index_str_mv) -->
                    <?php foreach ($indexData[$institution] as $category): ?>
                        <li>
                            <span class="category-name"><?= htmlspecialchars($category) ?></span>
                            <img src="<?=$this->imageLink('public/check.png')?>" alt="Icono" class="category-icon">
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php else: ?>
                <p>No hay indices disponibles.</p>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
