<?php  
function fetch_data($url) {
    $response = file_get_contents($url);
    if ($response === false) {
        return null;
    }
    $data = json_decode($response, true);
    if ($data === null) {
        return null; 
    }

    $numTopics = [];
    $categoryList = [];

    foreach ($data['response']['docs'] as $doc) {
        if (isset($doc['index_str_mv'])) {
            $numTopics[] = count($doc['index_str_mv']);
            $categoryList[] = $doc['index_str_mv'];
        } else {
            $numTopics[] = 0; 
            $categoryList[] = []; 
        }
    }

    return ['numTopics' => $numTopics, 'categoryList' => $categoryList];
}

$url = "http://localhost:8952/solr/biblio/select?fl=index_str_mv&fq=institution%3A%20Estudios%20Econ%C3%B3micos&indent=true&q.op=OR&q=*%3A*&useParams=";

$data = fetch_data($url);
$numTopics = $data['numTopics'];
$categoryList = $data['categoryList'];
?>

<h2>Índices</h2>
<div class="maindiv">
    <div class="accordion">
        <div class="accordion-item">
            <button data-target="content-1">
                <span class="button-text">Estudios de Asia y África</span>
                <span class="content-number"><?= $numTopics[0] ?? '0' ?></span>
                <i class="fa fa-chevron-down"></i>
            </button>
        </div>

        <div class="accordion-item">
            <button data-target="content-2">
                <span class="button-text">Historia Mexicana</span>
                <span class="content-number"><?= $numTopics[1] ?? '0' ?></span>
                <i class="fa fa-chevron-down"></i>
            </button>
        </div>



        <div class="accordion-item">
            <button data-target="content-3">
                <span class="button-text">Foro Internacional</span>
                <span class="content-number"><?= $numTopics[2] ?? '0' ?></span>
                <i class="fa fa-chevron-down"></i>
            </button>
        </div>

        <div class="accordion-item">
            <button data-target="content-4">
                <span class="button-text">Estudios Sociológicos de El Colegio de México</span>
                <span class="content-number"><?= $numTopics[3] ?? '0' ?></span>
                <i class="fa fa-chevron-down"></i>
            </button>
        </div>

        <div class="accordion-item">
            <button data-target="content-5">
                <span class="button-text">Estudios Demográfios y Urbanos</span>
                <span class="content-number"><?= $numTopics[4] ?? '0' ?></span>
                <i class="fa fa-chevron-down"></i>
            </button>
        </div>

        <div class="accordion-item">
            <button data-target="content-6">
                <span class="button-text">Cuadernos de Lingüística de El Colegio de México</span>
                <span class="content-number"><?= $numTopics[5] ?? '0' ?></span>
                <i class="fa fa-chevron-down"></i>
            </button>
        </div>


        <div class="accordion-item">
            <button data-target="content-7">
                <span class="button-text">Nueva Revista de Filología Hispánica</span>
                <span class="content-number"><?= $numTopics[6] ?? '0' ?></span>
                <i class="fa fa-chevron-down"></i>
            </button>
        </div>

        <div class="accordion-item">
            <button data-target="content-8">
                <span class="button-text">Revista Interdisciplinaria de Estudios de Género de El Colegio de México</span>
                <span class="content-number"><?= $numTopics[7] ?? '0' ?></span>
                <i class="fa fa-chevron-down"></i>
            </button>
        </div>

        <div class="accordion-item">
            <button data-target="content-9">
                <span class="button-text">Revista Estudios Económicos de El Colegio de México</span>
                <span class="content-number"><?= $numTopics[8] ?? '0' ?></span>
                <i class="fa fa-chevron-down"></i>
            </button>
        </div>
    </div>

    <!-- Contenido -->
    <div id="content-1" class="accordion-content">
        <?php if (!empty($categoryList[0])): ?>
            <ul class="category-list">
                <?php foreach ($categoryList[0] as $category): ?>
                <li > 
                    <span class="category-name"><?= htmlspecialchars($category) ?></span>
                    <img src="<?=$this->imageLink('public/check.png')?>" alt="Icono" class="category-icon">
                </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <p>No hay temas disponibles.</p>
        <?php endif; ?>
    </div>
    <div id="content-2" class="accordion-content">
    <?php if (!empty($categoryList[1])): ?>
            <ul class="category-list">
                <?php foreach ($categoryList[1] as $category): ?>
                <li > 
                    <span class="category-name"><?= htmlspecialchars($category) ?></span>
                    <img src="<?=$this->imageLink('public/check.png')?>" alt="Icono" class="category-icon">
                </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <p>No hay temas disponibles.</p>
        <?php endif; ?>
    </div>
    <div id="content-3" class="accordion-content">
    <?php if (!empty($categoryList[2])): ?>
            <ul class="category-list">
                <?php foreach ($categoryList[2] as $topic): ?>
                <li > 
                    <span class="category-name"><?= htmlspecialchars($category) ?></span>
                    <img src="<?=$this->imageLink('public/check.png')?>" alt="Icono" class="category-icon">
                </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <p>No hay temas disponibles.</p>
        <?php endif; ?>
    </div>
    <div id="content-4" class="accordion-content">
    <?php if (!empty($categoryList[3])): ?>
            <ul class="category-list">
                <?php foreach ($categoryList[3] as $category): ?>
                <li > 
                    <span class="category-name"><?= htmlspecialchars($category) ?></span>
                    <img src="<?=$this->imageLink('public/check.png')?>" alt="Icono" class="category-icon">
                </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <p>No hay temas disponibles.</p>
        <?php endif; ?>
    </div>
    <div id="content-5" class="accordion-content">
    <?php if (!empty($categoryList[4])): ?>
            <ul class="category-list">
                <?php foreach ($categoryList[4] as $category): ?>
                <li > 
                    <span class="category-name"><?= htmlspecialchars($category) ?></span>
                    <img src="<?=$this->imageLink('public/check.png')?>" alt="Icono" class="category-icon">
                </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <p>No hay temas disponibles.</p>
        <?php endif; ?>
    </div>
    <div id="content-6" class="accordion-content">
    <?php if (!empty($categoryList[5])): ?>
            <ul class="category-list">
                <?php foreach ($categoryList[5] as $category): ?>
                <li > 
                    <span class="category-name"><?= htmlspecialchars($category) ?></span>
                    <img src="<?=$this->imageLink('public/check.png')?>" alt="Icono" class="category-icon">
                </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <p>No hay temas disponibles.</p>
        <?php endif; ?>
    </div>
    <div id="content-7" class="accordion-content">
    <?php if (!empty($categoryList[6])): ?>
            <ul class="category-list">
                <?php foreach ($categoryList[6] as $category): ?>
                <li > 
                    <span class="category-name"><?= htmlspecialchars($category) ?></span>
                    <img src="<?=$this->imageLink('public/check.png')?>" alt="Icono" class="category-icon">
                </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <p>No hay temas disponibles.</p>
        <?php endif; ?>
    </div>
    <div id="content-8" class="accordion-content">
    <?php if (!empty($categoryList[7])): ?>
            <ul class="category-list">
                <?php foreach ($categoryList[7] as $category): ?>
                <li > 
                    <span class="category-name"><?= htmlspecialchars($category) ?></span>
                    <img src="<?=$this->imageLink('public/check.png')?>" alt="Icono" class="category-icon">
                </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <p>No hay temas disponibles.</p>
        <?php endif; ?>
    </div>
    <div id="content-9" class="accordion-content">
    <?php if (!empty($categoryList[8])): ?>
            <ul class="category-list">
                <?php foreach ($categoryList[8] as $category): ?>
                <li > 
                    <span class="category-name"><?= htmlspecialchars($category) ?></span>
                    <img src="<?=$this->imageLink('public/check.png')?>" alt="Icono" class="category-icon">
                </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <p>No hay temas disponibles.</p>
        <?php endif; ?>
    </div>
</div>

<script>
    const items = document.querySelectorAll('.accordion-item button');

    items.forEach(item => {
        item.addEventListener('click', () => {
            const targetId = item.getAttribute('data-target');
            const content = document.getElementById(targetId);
            const icon = item.querySelector('i');

            const isActive = content.classList.contains('active');

            const activeItem = document.querySelector('.accordion-content.active');
            const activeButton = document.querySelector('.accordion-item button.active');

            if (activeItem && activeItem !== content) {
                activeItem.classList.remove('active');
                const activeIcon = activeButton.querySelector('i.rotated');
                if (activeIcon) activeIcon.classList.remove('rotated');
                activeButton.classList.remove('active');
            }

            if (!isActive) {
                content.classList.add('active');
                icon.classList.add('rotated');
                item.classList.add('active');
            } else {
                content.classList.remove('active');
                icon.classList.remove('rotated');
                item.classList.remove('active');
            }
        });
    });

    //Funcion para cambiar de lugar el contenido en dispositivos mobiles y se muestren
    //debajo de su respectiva categoria
    function moveContentToAccordion() {
        const isMobile = window.innerWidth <= 480;
        const accordion = document.querySelector('.accordion');

        document.querySelectorAll('.accordion-content').forEach(content => {
            const targetId = content.id;
            const button = document.querySelector(`button[data-target="${targetId}"]`);

            if (isMobile) {
                button.insertAdjacentElement('afterend', content);
            } else {
                document.querySelector('.maindiv').appendChild(content);
            }
        });
    }

    function activateFirstAccordionItem() {
        if (window.innerWidth > 768) { 
            const firstItem = items[0];
            const firstContent = document.getElementById(firstItem.getAttribute('data-target'));
            const firstIcon = firstItem.querySelector('i');

            firstContent.classList.add('active');
            firstIcon.classList.add('rotated');
            firstItem.classList.add('active');
        }
    }

    window.addEventListener('resize', moveContentToAccordion);

    moveContentToAccordion();
    activateFirstAccordionItem();
</script>
</body>
</html>
