<div class="access-home">
  <div class="row">
    <div class="portal col-md-6">
      <a href="https://cic.umad.edu.mx/" target="_blank">
        <img src="<?=$this->imageLink('public/portal.png')?>" alt="Portal CIC">
        <h3>Portal CIC</h3>
      </a>      
    </div>
    <div class="repository col-md-6">
      <a href="https://dspace.umad.edu.mx/" target="_blank">
        <img src="<?=$this->imageLink('public/Repositorio.png')?>" alt="Portal CIC">
        <h3>Repositorio Institucional</h3>
      </a>
    </div>
  </div>
</div>