<div class="news-home">
  <div class="container">
    <div class="row">
      <h2 class="title">Últimas Noticias</h2>
      <div class="portal col-md-4">
        <a href="https://umad.edu.mx/tigres-blancos-umad-forjando-el-exito-a-traves-del-trabajo-en-conjunto/" target="_blank">
          <p class="title">Tigres Blancos UMAD: forjando el éxito
          a través del trabajo en conjunto</p>
          <img src="<?=$this->imageLink('public/Imagen1.png')?>" alt="news">
          <p>En la Jungla, la cancha de la Universidad Madero, los integrantes del equipo de futbol soccer realizan su preparación...</p>
        </a>      
      </div>
      <div class="repository col-md-4">
        <a href="https://umad.edu.mx/kick-off-de-practicas-y-estadias-profesionales/" target="_blank">
          <p class="title">KICK OFF de Prácticas y Estadías Profesionales</p>
          </br>
          <img src="<?=$this->imageLink('public/Imagen2.png')?>" alt="news">
          <p>San Andrés Cholula Puebla a 8 de agosto de 2024.-
            Un grupo de estudiantes de las diferentes
            licenciaturas de...</p>
        </a> 
      </div>
      <div class="repository col-md-4">
        <a href="https://umad.edu.mx/asi-luce-la-cancha-de-baloncesto-umad/" target="_blank">
          <p class="title">¡Así luce la cancha de baloncesto UMAD!</p>
          </br>
          <img src="<?=$this->imageLink('public/Imagen3.png')?>" alt="news">
          <p>San Andrés Cholula Pue., 5 de agosto de 2024.-
              Como parte de la materia "Campañas 360", los
              estudiantes de...</p>
        </a> 
      </div>
    </div>
  </div>
</div>