<footer class="hidden-print">
  <div class="footer-container">
  <div align="center" id="footer">
		<!-- <div class="col-md-12" id="div_footer">  <!-- Columnas para footer -->
			<div class="col-xs-12 col-md-2" id="footer_izq">
				<ul class="links">
					<li><a href="https://www.colmex.mx/es/centros" targte="_blank">Centros de Estudios</a></li>
					<li><a href="https://www.colmex.mx/es/programas" target="_blank">Programas docentes</a></li>
					<li><a href="https://biblioteca.colmex.mx/" target="_blank">Biblioteca</a></li>
					<li><a href=" https://agenda.colmex.mx/Inicio" target="_blank">Agenda</a></li>
					<li><a href="http://intranet.colmex.mx/directorio/" target="_blank">Directorio Institucional</a></li>
				</ul>
			</div>
			<div class="col-xs-12 col-md-8" id="footer_centro">
				<img id="img_footer" src="<?=$this->imageLink('public/colmex-pie.png')?>" alt="Colmex pie"><br>
				<a target="_blank" href="https://creativecommons.org/licenses/by-nc-nd/4.0/"><img id="img_cc" src="<?=$this->imageLink('public/creative-commons.png')?>" alt="Creative commons"></a>
				<p>Derechos reservados, El Colegio de México A.C. © 
<script type="text/javascript">
copyright=new Date();
update=copyright.getFullYear();
document.write(update);
</script>2024
<br>
	Carretera Picacho Ajusco 20, Col. Ampliación Fuentes del Pedregal, C.P. 14110 Tlalpan, Ciudad de México

	Tel.: +52 55 54493000</p>

			</div>
			<div class="col-xs-12 col-md-2" id="footer_der">
				<ul class="links">
					<li><a href="https://portal.office.com" target="_blank">Correo electrónico</a></li>
					<li><a href="https://intranet.colmex.mx/" target="_blank">Intranet</a></li>
					<li><a href="https://www.colmex.mx/es/mapa-sitio">Mapa de sitio</a></li>
					<li><a href="https://www.colmex.mx/es/como-llegar">Cómo llegar</a></li>
					<li class="no-border"><a href="https://revistas.colmex.mx/aviso/">Aviso de Privacidad</a></li>
				</ul>
			</div>
		<!-- </div> <!-- Cierre de columnas para footer -->

	<div class="col-xs-12 col-md-12" id="redes_footer"> <!-- Columnas para redes sociales en footer-->
			<ul class="botones_footer">
				<a target="_blank" href="https://www.facebook.com/elcolmex/"><img class="img_net" src="<?=$this->imageLink('public/fb-bco.png')?>" alt="Fb bco"></a>
				<a target="_blank" href="https://twitter.com/ELCOLMEX"><img class="img_net" src="<?=$this->imageLink('public/twitter-bco.png')?>" alt="Twitter bco"></a>
				<a target="_blank" href="https://www.youtube.com/c/elcolegiodemexicociudaddemexico"><img class="img_net" src="<?=$this->imageLink('public/youtube-bco.png')?>" alt="Youtube bco"></a>
				<a target="_blank" href="https://itunes.apple.com/mx/institution/el-colegio-de-mexico/id443160573"><img class="img_net" src="<?=$this->imageLink('public/itunes-bco.png')?>" alt="Itunes bco"></a>
				<a target="_blank" href="https://www.linkedin.com/edu/el-colegio-de-m%C3%A9xico-14986"><img class="img_net" src="<?=$this->imageLink('public/linkedin-bco.png')?>" alt="Linkedin bco"></a>
				<!--<a target="_blank" href="https://plus.google.com/+ElColegiodeMéxico081040"><img class="img_net" src="<?=$this->imageLink('public/google-bco.png')?>" alt="Google bco"></a>-->
				<a target="_blank" href="https://www.instagram.com/elcolmex/"><img class="img_net" src="<?=$this->imageLink('public/instagram-bco.png')?>" alt="Instagram bco"></a>
				<a target="_blank" href="https://podcasts.apple.com/mx/podcast/el-colmex-conocimiento-ciencia-y-cultura/id1554015844?l=en"><img class="img_net" src="<?=$this->imageLink('public/podcast-bco.png')?>" alt="Podcast bco"></a>
				<a target="_blank" href="https://open.spotify.com/show/4bJyTYlgHMb3gKo6jtKm2D"><img class="img_net" src="<?=$this->imageLink('public/spotify-bco.png')?>" alt="Spotify bco"></a>
				<!--<a target="_blank" href="https://soundcloud.com/elcolmex/"><img class="img_net" src="<?=$this->imageLink('public/soundcloud-blanco.png')?>" alt="Soundcloud blanco"></a>-->
			</ul>

		</div> <!-- Cierre de columnas para redes sociales en footer -->


</div>
</footer>
