<?php $account = $this->auth()->getManager(); ?>
<div class="navbare">
  <a href="https://www.colmex.mx/" class="fr" target="_blank">Colmex</a>
  <a href="http://portal.office.com/" class="fr" target="_blank"><img src="<?=$this->imageLink('public/mail.png')?>" alt="Mail">&nbsp;Correo electrónico</a>
  <a href="http://intranet.colmex.mx/" class="fr" target="_blank"><img src="<?=$this->imageLink('public/intranet.png')?>" alt="Mail">&nbsp;Intranet</a>

<div style="float:right; margin-top: 4px; margin-right: 1em;">
	<a href="https://www.facebook.com/elcolmex/" target="_blank"><img class="img_net" style="width: 12px !important;" src="<?=$this->imageLink('public/fb.png')?>" alt="Fb vino"></a>&nbsp;
	<a href="https://twitter.com/ELCOLMEX" target="_blank"><img class="img_net" src="<?=$this->imageLink('public/twitter.png')?>" alt="Twitter vino"></a>&nbsp;
	<a href="https://www.youtube.com/c/elcolegiodemexicociudaddemexico" target="_blank"><img class="img_net" src="<?=$this->imageLink('public/youtube.png')?>" alt="Youtube vino"></a>&nbsp;
	<a href="https://itunes.apple.com/mx/institution/el-colegio-de-mexico/id443160573" target="_blank"><img class="img_net" src="<?=$this->imageLink('public/itunes.png')?>" alt="Itunes vino"></a>&nbsp;
	<a href="https://www.linkedin.com/edu/el-colegio-de-m%C3%A9xico-14986" target="_blank"><img class="img_net" src="<?=$this->imageLink('public/linkedin-vino.png')?>" alt="Linkedin vino"></a>&nbsp;
	<!--<a href="https://plus.google.com/+ElColegiodeM%C3%A9xico081040" target="_blank"><img class="img_net" src="<?=$this->imageLink('public/google.png')?>" alt="Google vino"></a>&nbsp;-->
	<a href="https://www.instagram.com/elcolmex/" target="_blank"><img class="img_net" src="<?=$this->imageLink('public/instagram.png')?>" alt="Instagram vino">&nbsp;
	</a><a target="_blank" href="https://podcasts.apple.com/mx/podcast/el-colmex-conocimiento-ciencia-y-cultura/id1554015844?l=en"><img class="img_net" src="<?=$this->imageLink('public/podcast-vino.png')?>" alt="Podcast bco"></a>
	<a target="_blank" href="https://open.spotify.com/show/4bJyTYlgHMb3gKo6jtKm2D"><img class="img_net" src="<?=$this->imageLink('public/spotify-vino.png')?>" alt="Spotify bco"></a>
	<!--<a href="https://soundcloud.com/elcolmex" target="_blank"><img class="img_net" src="<?=$this->imageLink('public/soundcloud.png')?>" alt="Soundcloud vino"></a>-->
</div>
</div>
<div class="banner container navbar">
  <div>
    <img class="img_net" src="<?=$this->imageLink('public/Banner.png')?>" alt="Spotify bco"></a>
  </div>
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse" aria-label="<?=$this->transEscAttr('mobile_toggle_navigation_text')?>">
      <?=$this->icon('ui-menu') ?>
    </button>
  </div>
  <?php if (!isset($this->layout()->renderingError)): ?>
    <div class="collapse navbar-collapse" id="header-collapse">
      <nav>
        <ul class="nav navbar-nav navbar-right flip">
          <li>
            <a class="navbar-brand lang-<?=$this->layout()->userLang ?>" href="<?=$this->url('home')?>"><?=$this->transEsc('Home')?></a>
          </li>
          <li>
            <a href="<?=$this->url('content-page', ['page' => 'indexes']) ?>"> índices</a>
          </li>
          <li>
            <a href="<?=$this->url('content-page', ['page' => 'statistics']) ?>">Estadísticas</a>
          </li>
          <li>
            <a href="<?=$this->url('content-page', ['page' => 'search']) ?>"><?=$this->transEsc('Search')?></a>
          </li>
          
          <?php if ($this->feedback()->tabEnabled()): ?>
            <li>
              <a class="icon-link" id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>">
                <?=$this->icon('feedback', 'icon-link__icon') ?>
                <span class="icon-link__label"><?=$this->transEsc('Feedback')?></span>
              </a>
            </li>
          <?php endif; ?>
          <?php $cart = $this->cart(); ?>
          <?php if ($cart->isActive()): ?>
            <li id="cartSummary" aria-live="polite" aria-atomic="true">
              <a id="cartItems" class="icon-link" data-lightbox title="<?=$this->transEscAttr('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                <?=$this->icon('cart', 'icon-link__icon') ?>
                <span class="icon-link__label">
                  <span class="sr-only"><?=$this->transEsc('Book Bag')?>:</span>
                  <span role="status"><strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?></span>
                  <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc('bookbag_full') ?>)</span>
                </span>
              </a>
            </li>
          <?php endif; ?>
          <?php if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
            <?php if ($account->getIdentity()): ?>
              <li class="logoutOptions<?php if ($account->dropdownEnabled()): ?> with-dropdown<?php endif ?>">
                <a href="<?=$this->url('myresearch-home', [], ['query' => ['redirect' => 0]])?>" class="icon-link">
                  <span id="account-icon" class="icon-link__icon"><?=$this->icon('my-account') ?></span>
                  <span class="icon-link__label"><?=$this->transEsc('Your Account')?></span>
                </a>
              </li>
              <?php if ($account->dropdownEnabled()): ?>
                <li id="login-dropdown" class="dropdown hidden-xs">
                  <a href="#" data-toggle="dropdown"><?=$this->icon('dropdown-caret') ?></a>
                  <div class="dropdown-menu">
                    <?=$this->accountMenu()->render('', 'header_')?>
                  </div>
                </li>
              <?php endif; ?>
              <li class="logoutOptions">
                <a href="<?=$this->url('myresearch-logout')?>" class="logout icon-link">
                  <?=$this->icon('sign-out', 'icon-link__icon') ?>
                  <span class="icon-link__label"><?=$this->transEsc('Log Out')?></span>
                </a>
              </li>
            <?php else: ?>
              <li id="loginOptions">
                <?php if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                  <a href="<?=$this->url('myresearch-userlogin')?>" class="icon-link">
                    <?=$this->icon('sign-in', 'icon-link__icon') ?>
                    <span class="icon-link__label"><?=$this->transEsc('Institutional Login')?></span>
                  </a>
                <?php else: ?>
                  <a href="<?=$this->url('myresearch-userlogin')?>" class="icon-link" data-lightbox>
                    <?=$this->icon('sign-in', 'icon-link__icon') ?>
                    <span class="icon-link__label"><?=$this->transEsc('Login')?></span>
                  </a>
                <?php endif; ?>
              </li>
            <?php endif; ?>
          <?php endif; ?>

          <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
              <?=$this->component('menu-button', [
                  'toggleLabel' => 'Theme',
                  'wrapperClass' => 'theme-selector',
                  'wrapperTag' => 'li',
                  'menuItems' => array_map(
                      function ($item) {
                          $item['label'] = $item['desc'];
                          $item['url'] = $this->url()->addQueryParameters(['ui' => $item['name']]);

                          return $item;
                      },
                      $this->layout()->themeOptions
                  ),
              ]) ?>
          <?php endif; ?>

          <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
              <?=$this->component('menu-button', [
                  'toggleLabel' => 'Language',
                  'wrapperClass' => 'language',
                  'wrapperTag' => 'li',
                  'menuItems' => array_map(
                      function ($langCode, $langName) {
                          return [
                            'label' => $this->displayLanguageOption($langName),
                            'url' => $this->url()->addQueryParameters(['lng' => $langCode]),
                            'selected' => $this->layout()->userLang == $langCode,
                          ];
                      },
                      array_keys($this->layout()->allLangs),
                      array_values($this->layout()->allLangs),
                  ),
              ]) ?>
          <?php endif; ?>
        </ul>
      </nav>
    </div>
  <?php endif; ?>
</div>
<?php if ($this->layout()->searchbox !== false): ?>
  <div class="search container navbar">
    <div class="nav searchbox hidden-print" role="search">
      <?=$this->layout()->searchbox ?>
    </div>
  </div>
<?php endif; ?>
